spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${SENHA}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000

viacep:
  url: https://viacep.com.br/ws

logging:
  level:
    feign: DEBUG
    com.marcaaiback.client: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: FULL

jwt:
  secret: ${JWT_SECRET}

n8n:
  url:
    notificacao-admin: ${N8N_NOTIFICACAO_ADMIN_URL}